package com.hnisc.community.mapper;

import com.hnisc.community.model.Post;
import com.hnisc.community.model.PostExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository("PostMapper.xml")
public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    List<Post> selectByExampleWithBLOBsWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    List<Post> selectByExampleWithBLOBs(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    List<Post> selectByExampleWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_post
     *
     * @mbg.generated Mon Dec 09 18:02:15 GMT+08:00 2019
     */
    int updateByPrimaryKey(Post record);
}