package com.hnisc.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.parent_id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.parent_type
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Integer parentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.commentator_id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Long commentatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.gmt_create
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.gmt_modified
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.like_count
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.dislike_count
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private Integer dislikeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_comment.description
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.id
     *
     * @return the value of ic_comment.id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.id
     *
     * @param id the value for ic_comment.id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.parent_id
     *
     * @return the value of ic_comment.parent_id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.parent_id
     *
     * @param parentId the value for ic_comment.parent_id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.parent_type
     *
     * @return the value of ic_comment.parent_type
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Integer getParentType() {
        return parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.parent_type
     *
     * @param parentType the value for ic_comment.parent_type
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setParentType(Integer parentType) {
        this.parentType = parentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.commentator_id
     *
     * @return the value of ic_comment.commentator_id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Long getCommentatorId() {
        return commentatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.commentator_id
     *
     * @param commentatorId the value for ic_comment.commentator_id
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setCommentatorId(Long commentatorId) {
        this.commentatorId = commentatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.gmt_create
     *
     * @return the value of ic_comment.gmt_create
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.gmt_create
     *
     * @param gmtCreate the value for ic_comment.gmt_create
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.gmt_modified
     *
     * @return the value of ic_comment.gmt_modified
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.gmt_modified
     *
     * @param gmtModified the value for ic_comment.gmt_modified
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.like_count
     *
     * @return the value of ic_comment.like_count
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.like_count
     *
     * @param likeCount the value for ic_comment.like_count
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.dislike_count
     *
     * @return the value of ic_comment.dislike_count
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public Integer getDislikeCount() {
        return dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.dislike_count
     *
     * @param dislikeCount the value for ic_comment.dislike_count
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setDislikeCount(Integer dislikeCount) {
        this.dislikeCount = dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_comment.description
     *
     * @return the value of ic_comment.description
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_comment.description
     *
     * @param description the value for ic_comment.description
     *
     * @mbg.generated Fri Dec 13 23:14:24 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}